### PR TITLE
fix #1508

### LINKED ISSUE #1508: Unexpected error: Cannot read property 'webContents' of undefined
### Description

An unexpected error occurred in the main process.

1. edit a file and don't save it
2. a window says "Do you want to save the changes you made to 1 file?
" will pop up when you try to close the window
3. click `File -> Export -> HTML` or click `About Mark Text`
4. an error occurred 

### Stack Trace

```
TypeError: Cannot read property 'webContents' of undefined
    at Et (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:292449)
    at click (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:293844)
    at MenuItem.click (/Applications/Mark Text.app/Contents/Resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/Applications/Mark Text.app/Contents/Resources/electron.asar/browser/api/menu.js:31:13)
```

### Version

Mark Text: v0.15.1
Operating system: Darwin x64 18.7.0 (darwin)

### PR DESCRIPTION
**Pull request by Jocs**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| Fixed tickets    | #1508
| License          | MIT

### Description

[Description of the bug or feature]

--

#### Please, don't submit `/dist` files with your PR!

---
This change is [Reviewable](https://reviewable.io/reviews/marktext/marktext/1536)

### CODE REVIEW

File: src/main/menu/actions/edit.js [hunk 1]
```diff
@@ -22,13 +22,17 @@ ipcMain.on('mt::ask-for-image-auto-path', (e, { pathname, src, id }) => {
...
+  }
 }
 
 export const screenshot = (win, type) => {
   ipcMain.emit('screen-capture', win)
 }
 
 export const lineEnding = (win, lineEnding) => {
-  win.webContents.send('AGANI::set-line-ending', { lineEnding, ignoreSaveStatus: false })
+  if (win.webContents) {
```
Comment (fxha) [inline src/main/menu/actions/edit.js]: We need to check window first (`win && win.webContents`)?

Comment (Jocs) [reply src/main/menu/actions/edit.js]: Yes, my fault.

**Comment by Jocs** [comment]
@fxha fixed.
