### PR TITLE
fix: #2836 fix formula first render

### LINKED ISSUE #2836: The arrow in the formula shows the problem
### Description

There is a strange phenomenon. When I write this formula for the first time, the arrow of the vector can be displayed, but it can't be displayed when I open it again. I have to click it again to display the arrow.

eg.

```
$$
\overrightarrow{HC} \cdot \overrightarrow{AB} = 
\overrightarrow{HC} \cdot \overrightarrow{AC} + \overrightarrow{HC} \cdot \overrightarrow{CB} =
\overrightarrow{BC} \cdot \overrightarrow{AC} - \overrightarrow{AC} \cdot \overrightarrow{BC} = 0
$$
```

**first write**

image

**open again**
image

### Versions

- MarkText version: 0.16.3
- Operating system: mac

### PR DESCRIPTION
**Pull request by toSayNothing**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| Breaking changes? | no
| Deprecations?     | no
| New tests added?  | not needed
| Fixed tickets     | #2836
| License           | MIT

### Description

[Description of the bug or feature]
close #2836;
https://github.com/marktext/marktext/blob/4c517b163232af5649b7a26d4a5705e40bbe4817/src/muya/lib/parser/render/index.js#L183
the reason: snabbdom `patch` fn doesn't parse SVGs correctly , Related issue [#388](https://github.com/snabbdom/snabbdom/issues/388), i had tried update snabbdom to version 2.1.0, but didn't work.
so we need to refresh the svg , use innerHTML.
```js
patch(oldVdom, newVdom)
const refreshSvgParent = (vDom) => {
  if (vDom.children?.some(e => e.sel === 'svg')) {
    const html = vDom.elm.innerHTML
    vDom.elm.innerHTML = html
  } else vDom.children?.forEach(v => refreshSvgParent(v))
}
refreshSvgParent(newVdom)
```
**before-fix**
before-fix

**after-fix**
after-fix

### CODE REVIEW

**Comment by fxha** [comment]
@Jocs Any plans to update `snabbdom` library in Muya? Are there significant improvement over the current version?

**Comment by toSayNothing** [comment]
I also think updating or replacing the `patch` library is a better idea. Because recursion virtual dom children after each `patch` is a little too expensive

**Comment by Jocs** [comment]
@toSayNothing Does snabbdom 3.2.0 solve this problem?

**Comment by Jocs** [comment]
@fxha I'll update some marjor dependences of muya before the next MarkText release, maybe the next week.

BTY, do you think is it necessary to update `marked` to the latest version?

**Comment by toSayNothing** [comment]
@Jocs no, the problem still exits in 3.2.0, here is the online demo : https://stackblitz.com/edit/js-bzujnd?file=index.js 
image

**Comment by toSayNothing** [comment]
@fxha @Jocs  I think the reason is: in snabbdom document
>SVG just works when using the h function for creating virtual nodes. 

so when we convert the real dom to virtual dom, we use the `toVNode` fn, which will miss the data.ns attribute, so we can add data.ns after virtual dom is created, and therefore don't need to use innerHTML to refresh the dom after `patch`.

**Comment by Jocs** [comment]
@toSayNothing Does snabbdom have plans to fix this? Or can we submit a PR to snabbdom to fix this?

**Comment by toSayNothing** [comment]
I have asked the snabbdom maintainer, wait for a reply now. https://github.com/snabbdom/snabbdom/issues/388

**Comment by Jocs** [comment]
@toSayNothing A [PR](https://github.com/snabbdom/snabbdom/pull/996 ) is submited, so we can wait for this PR merged, and update snabbdom?

**Comment by toSayNothing** [comment]
I think so.😅

**Comment by fxha** [comment]
@Jocs Could we merge this and update snabbdom after the upstream PR is merged. This would guarantee a working version in our next release.

**Comment by Jocs** [comment]
>Could we merge this and update snabbdom after the upstream PR is merged. This would guarantee a working version in our next release.

Ok, We need to submit a issue to track this(update snabbdom)?

**Comment by fxha** [comment]
You can create an issue if you want or note down and update the lib :smile:

**Review by fxha — APPROVED** [review]

File: src/muya/lib/parser/render/snabbdom.js [hunk 1]
```diff
@@ -17,3 +17,19 @@ export const htmlToVNode = html => { // helper function for convert html to vnod
...
+    children.filter((vNode) => vNode.data).forEach(addNS)
+  }
+}
+
+export const addNStoVNodeChildren = (children = []) => {
+  children
+    .filter((vNode) => vNode.data)
+    .forEach((vNode) => {
+      addNStoVNodeChildren(vNode.children)
+      vNode.sel.startsWith('svg') && addNS(vNode)
```
Comment (fxha) [inline src/muya/lib/parser/render/snabbdom.js:33]: Please use if-condition for readability.

Comment (toSayNothing) [reply src/muya/lib/parser/render/snabbdom.js]: I have pushed a new commit, cc😅

**Review by Jocs — APPROVED** [review]
