### PR TITLE
fix: #929

### LINKED ISSUE #929: scroll error when input mermaid diagram
### Description

There is a very long scroll bar after I input a mermaid diagram.

```md
\```mermaid
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail...
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
\```
```

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. create a mermaid above.
2. create a paragraph bellow.
3. put the cursor in the bellow paragraph.

**Expected behavior:**

You should not see the scroll bar.

**Actual behavior:**

Mark Text show a very long scroll bar.

**Link to an example: [optional]**

### Versions

- Mark Text: v0.14.0
- Operating system: All

### PR DESCRIPTION
**Pull request by Jocs**
@fxha I have modified this PR, only for fix #929 and other little code optimization.

fix #929

### CODE REVIEW

File: src/muya/lib/index.js [hunk 1]
```diff
@@ -74,6 +74,11 @@ class Muya {
             if (hasTable) {
               console.warn('There was a problem with the table deletion.')
             }
+            const lineRemovedUnExpected = Array.from(removedNodes).some(node => node.nodeType === 1 && node.classList.contains('ag-paragraph-content'))
```
Comment (fxha) [inline src/muya/lib/index.js]: I think this should be named `lineRemovedUnexpected` because `un` is just a prefix and please add a comment and/or link to the associated GitHub issue of better understanding.
