### PR TITLE
Fix symbolic links and related path issues

### LINKED ISSUE #2325: Can not open 2. file with `--new-window` option
### Description

When I open a second file with `--new-window` MartText shows a blank page.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open first file:

       marktext --new-window first.md

2. Open second file:

       marktext --new-window second.md

**Expected behavior:**

The second file opens in another instance of MarkText.

**Actual behavior:**

Instead of `second.md` a blank page is shown.

### Versions

- Mark Text version:     16.2
- Operating system: Debian 10.5

### LINKED ISSUE #2355: Unexpected error: The "path" argument must be of type string. Received type object
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.isAbsolute (path.js:1030:5)
    at IpcMainImpl.<anonymous> (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:235097)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3908:15)
    at WebContents.emit (events.js:210:5)
```

### Version

Mark Text: v0.16.2
Operating system: Darwin x64 19.6.0 (darwin)

### LINKED ISSUE #2373: Mark Text fails to open symlinkes
Mark Text fails to open symlinked files and folders in version 0.16.2 (I'm running Linux Mint 18.3). Trying to open a symlinked file or right clicking on a symlinked folder and trying to open it will result in Mark Text starting but with an empty document. Other text editors are able to open the same files and folders.

### PR DESCRIPTION
**Pull request by fxha**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Fixed tickets     | fixes #2373, fixes #2325, fixes #2355
| License           | MIT

### Description

1. Fixed file and directory detection on symbolic links.
2. Fixed an issue that the file list disappears when launching Mark Text with `--new-window`.
3. Fixed an issue that an empty editor was opened when you cancel the file selection dialog.
4. The PR should also fix #2355.

### CODE REVIEW

File: src/main/menu/actions/edit.js [hunk 1]
```diff
@@ -5,6 +5,11 @@ import { searchFilesAndDir } from '../../utils/imagePathAutoComplement'
 
 ipcMain.on('mt::ask-for-image-auto-path', (e, { pathname, src, id }) => {
   const win = BrowserWindow.fromWebContents(e.sender)
+  if (!src || src !== 'string') {
```
Comment (Jocs) [inline src/main/menu/actions/edit.js:8]: Do you lost `typeof` ?

`typeof src !== 'string'`

**Review by Jocs — APPROVED** [review]

**Review by Jocs — APPROVED** [review]

**Comment by Jocs** [comment]
looks good to me.
