### PR TITLE
fix #1297

### LINKED ISSUE #1297: Linked images are not rendered
Linked images do not work as expected. 

See the comparison between Typora and Mark Text:

Typora and MarkText

Here is the relevant markdown text:
`````
# MIDDLEWARE CSP-PKCS11 PER LA CIE 3.0 [![Build status]
(https://ci.appveyor.com/api/projects/status/dpc0Oditjn04ylw6y?svg=true)]
(https://ci.appveyor.com/project/italia/cie-middleware)
`````

### PR DESCRIPTION
**Pull request by Jocs**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| Fixed tickets    | #1297 
| License          | MIT

### Description

[Description of the bug or feature]

--

### CODE REVIEW

File: src/muya/lib/utils/index.js [hunk 1]
```diff
@@ -166,6 +166,8 @@ export const checkImageContentType = url => {
         } else {
           settle(false)
         }
+      } else if (req.status === 405) { // status 405 means method not allowed, and just return true
+        settle(true)
```
Comment (fxha) [inline src/muya/lib/utils/index.js]: I think you should reference to the issue, so that we later know why we did this :smile:

Comment (Jocs) [reply src/muya/lib/utils/index.js]: Ok!
