### PR TITLE
fix clickable HTML links on Windows (#3015)

### LINKED ISSUE #3015: Bugs in local file link after upgrading to 0.17.0-rc.1?
### Description

I previously use 0.16.3 and everything works fine. After upgrading to 0.17.0-rc.1, I find all my file links are ineffective. The hyperlinks to websites work as usual.

### Steps to reproduce

 For example, suppose my `D:\Notes\note.md` contains the following link to a new markdown file named `D:\file\new_note.md`: `[hello_world](D:\file\new_note.md)`. However, the file cannot be opened: `Windows cannot find file "D:\Notes\hello_world". Please check the file name is correct, and try again.` It seems the `hello_world` is used for the file name. 

**Expected behavior:**

`new_note.md` can be opened as usual.

**Actual behavior:**

Windows cannot find file "D:\Notes\hello_world". Please check the file name is correct, and try again.

### Versions

- MarkText version: 0.17.0-rc.1
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by fxha**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Fixed tickets     | Fixes #3015
| License           | MIT

### Description

Fixed clickable HTML links (`<a href="C:\a.md">foo</a>`) on Windows because the `href` was filtered out by dompurify. This PR applies a patch to Muya to map paths like `C:\foo\bar\doc.md` to an UNC path `\\\\?\\C:\foo\bar\doc.md` on Windows that is allowed by the validator.

### CODE REVIEW

File: src/muya/lib/utils/url.js [hunk 1]
```diff
@@ -1,8 +1,22 @@
...
-    return rawLink
+  if (rawLink && typeof rawLink === 'string') {
+    if (isValidAttribute('a', 'href', rawLink)) {
+      return rawLink
+    }
+
+    // __MARKTEXT_PATCH__
+    if (isWin && /^[a-zA-Z]:[/\\].+/.test(rawLink) && hasMarkdownExtension(rawLink)) {
+      // Create and try UNC path on Windows because "C:\file.md" isn't allowed.
+      const uncPath = `\\\\?\\${rawLink}`
```
Comment (Jocs) [inline src/muya/lib/utils/url.js:14]: We add `\\\\?\\` prefix, can we still open the link?

**Review by Jocs — APPROVED** [review]

File: src/muya/lib/utils/url.js (hunk 1 above)
Comment (fxha) [reply src/muya/lib/utils/url.js:14]: `\\?\` is a local  UNC path that is supported by Windows to allow paths with a length larger 255 and to connect network drives from external servers/IPs. I'm unsure whether this will for for network drives but it will for the common cases.
