### PR TITLE
Fix double used shortcut

### LINKED ISSUE #2040: Pressing the Focus Mode shortcut brings up the Search Sidebar
### Description

When I press the shortcut for entering Focus Mode (Ctrl+Shift+F), Mark Text instead opens the Search sidebar. It does not enter Focus Mode. Pressing the shortcut again while the search sidebar is open has no effect.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open a file, or create a new file
2. Press Ctrl+Shift+F

**Expected behavior:**

Mark Text should enter Focus Mode.

**Actual behavior:**

The Search Sidebar opens.

**Link to an example:**

2020-04-11 21_24_47-Untitled-1 - Drafts

### Versions

- Mark Text: 0.16.1
- Operating system: Windows 10 Home 64-bit

### PR DESCRIPTION
**Pull request by fxha**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| Fixed tickets     | fixes #2040
| License           | MIT

### Description

Fix double used shortcut for search in folder and focus mode by using `Ctrl+Shift+J` to toggle focus mode. I also changed to "open folder" button when no folder is opened to be consistent to the other UI.

### CODE REVIEW

File: src/main/keyboard/shortcutHandler.js [hunk 1]
```diff
@@ -99,7 +99,7 @@ class Keybindings {
       ['view.command-palette', 'CmdOrCtrl+Shift+P'],
       ['view.source-code-mode', 'CmdOrCtrl+Alt+S'],
       ['view.typewriter-mode', 'CmdOrCtrl+Alt+T'],
-      ['view.focus-mode', 'CmdOrCtrl+Shift+F'],
+      ['view.focus-mode', 'CmdOrCtrl+Shift+J'],
```
Comment (Jocs) [inline src/main/keyboard/shortcutHandler.js:102]: Do you also need to update the documents in `docs/KEYBINDINGS.md` ?
