### PR TITLE
fix: #2720 Alt gr problem on other keyboard layouts

### LINKED ISSUE #2720: Alt gr problem on other keyboard layouts
https://github.com/marktext/marktext/blob/cb8b031753290e84c0da7db80b971934ccb56032/src/main/keyboard/shortcutHandler.js#L109

I think that this make the issue with alt gr and number keys that are binded with @#$~&*{} etc.

### PR DESCRIPTION
**Pull request by csingewald**
| Q                 | A
| ----------------- | ---
| Bug fix?          | yes
| New feature?      | no
| Breaking changes? | no
| Deprecations?     | no
| New tests added?  | not needed
| Fixed tickets     | Fixes #2720 number (set to none if no tickets are fixed, repeat template for each ticket fixed)
| License           | MIT

### Description

Alt gr problem on other keyboard layouts

Use "Ctrl" on osx instead of "Alt"

### CODE REVIEW

File: src/main/keyboard/shortcutHandler.js [hunk 1]
```diff
@@ -8,6 +8,7 @@ import { isFile2 } from 'common/filesystem'
 import { isOsx } from '../config'
 import { getKeyboardLanguage, getVirtualLetters } from '../keyboard'
 
+const altOrCtrl = (isOsx) ? 'Ctrl' : 'Alt'
```
Comment (fxha) [inline src/main/keyboard/shortcutHandler.js:11]: Please use a better name like `tabSwitchBaseStroke` or similar.

**Review by fxha — COMMENTED** [review]
Thanks @csingewald for your fix. I think we have a general problem with these shortcuts after reading multiple issues. I think the best way would be to remap the keys for all OSs. I'm trying to find a solution that fixes the issues once and for all. I'll /cc you.

Cmd and Ctrl are two different key on macOS, right? We're already using `CmdOrCtrl` for `paragraph.heading-<num>`

File: src/main/keyboard/shortcutHandler.js (hunk 1 above)
Comment (csingewald) [reply src/main/keyboard/shortcutHandler.js]: Yes on mac crtrl and cmd are different keys. Most apps use slightly different mappings on macos.

**Review by fxha — APPROVED** [review]
