### PR TITLE
Fix keybinding issues

### LINKED ISSUE #216: Key binding does not work
已经将 `user perference` 下的`aido`设置为`true`了但是仍然不能用`ｃｔｒｌ+/`呼出界面

### LINKED ISSUE #311: CTRL+Z not working
### Description

Pressing `CTRL+Z` doesn't do anything.

### Steps to reproduce

1. Type some text
2. Delete some text
3. `CTRL+Z`

**Expected behavior:** That the deleting text gets undone

**Actual behavior:** Nothing happens

### Versions

- Mark Text: v 0.11.42
- OS: Windows 10

### LINKED ISSUE #346: text formatting shortcuts are counter intuitive
### Description

Bold, Italics have a standard key binding across apps.
It is counter-intuitive to use different key bindings.

- Bold should be `command + b`
- italicize / emphasis should be `command + i`

### Versions

- Mark Text: 0.12.20
- OS: macOS

### PR DESCRIPTION
**Pull request by fxha**
| Q                | A
| ---------------- | ---
| Bug fix?         | yes
| New feature?     | yes
| BC breaks?       | yes
| Fixed tickets    | #216 #311 #346
| License          | MIT

### Description

Please try out the new key bindings and give feedback.

Prebuilt binaries for Linux and Windows are available [here](https://github.com/marktext/marktext/releases/tag/KeybindingFixes).

---

You need a (modern) C++ compiler to build Mark Text because this PR adds native libraries.

---

- added: user-defined key bindings `keybindings.json` e.g:
```json
{
  "fileSave": "CmdOrCtrl+S",
  "fileSaveAs": "CmdOrCtrl+Shift+S"
}
```
- added: basic CLI interaction
- fix keybindings on Linux and Windows
  - workaround for dead keys and non-US keyboard layouts
- change a few keybinding
  - Quit: `Alt+F4` (Linux and Windows)
  - Create HTML block: `CmdOrCtrl+Alt+H`
  - Strong: `CmdOrCtrl+B`
  - Emphasis: `CmdOrCtrl+I`
- Switching your keyboard layout while running Mark Text is undefined. It may break shortcuts.

fix #216
fix #311
resolves #346

**Not resolved issues:**

- You can use shortcuts in source code mode
- Redo doesn't work on Linux and Windows (#542)

**TODOs:**

- ~~Add settings option `keyboard-lang` to overwrite keyboard language~~

### CODE REVIEW

File: src/main/shortcutHandler.js [hunk 1]
```diff
@@ -0,0 +1,245 @@
...
+      return
+    }
+
+    // keybindings.json example:
+    // {
+    //   "fileSave": "CmdOrCtrl+S",
+    //   "fileSaveAs": "CmdOrCtrl+Shift+S"
+    // }
+
+    // TODO: should we check for duplicate shortcuts
```
Comment (Jocs) [inline src/main/shortcutHandler.js]: Good idea, we can check the duplicate shortcuts when we add new shortcut.

**Comment by Jocs** [comment]
>You can use shortcuts in source code mode

This is mentioned in roadmap, which will later refactor the source code mode editor and then support shortcuts.

>Fix Travis CI because native dependencies will break build process.

Can we solve this? or we need a VM?

**Comment by Jocs** [comment]
>Create HTML block: CmdOrCtrl+Alt+H
>Strong: CmdOrCtrl+B
>Emphasis: CmdOrCtrl+I

It works 👍

**Comment by Jocs** [comment]
I haven't reviewed the code carefully yet. I will review the code tomorrow, great PR, and solve a lot of headaches.

**Comment by fxha** [comment]
> > You can use shortcuts in source code mode
>
> This is mentioned in roadmap, which will later refactor the source code mode editor and then support shortcuts.

The problem is that you can use shortcuts in source code mode and this will result in a lot of renderer exceptions - as in the current builds.

> >Fix Travis CI because native dependencies will break build process.
>
> Can we solve this? or we need a VM?

Yes, we just have to change one line and enable AppVeyor as Windows CI. It's free for open source software.

**Comment by Jocs** [comment]
>The problem is that you can use shortcuts in source code mode and this will result in a lot of renderer exceptions - as in the current builds.

I understand what you mean now, I'll take a look at this.

>Yes, we just have to change one line and enable AppVeyor as Windows CI. It's free for open source software.

Nice!

File: src/main/shortcutHandler.js (hunk 1 above)
Comment (fxha) [reply src/main/shortcutHandler.js]: The code is a little messed up.

**Comment by Jocs** [comment]
@fxha FYI, https://issuehunt.io/repos/110446844/issues/346

File: src/main/shortcutHandler.js [hunk 2]
```diff
@@ -0,0 +1,295 @@
...
+  fixAidou () {
+    this.mnemonics.set('CmdOrCtrl+/', 'CmdOrCtrl+7')
+  }
+
+  // fix dead backquote key on layouts like German
+  fixInlineCode () {
+    this.keys.set('formatInlineCode', 'CmdOrCtrl+Shift+B')
+  }
+
+  loadLocalKeybindings () {
```
Comment (Jocs) [inline src/main/shortcutHandler.js]: Do we need to add some docs about how to add custom keybindings in the docs folder, and refer in the `README.md` file.

File: src/main/shortcutHandler.js [hunk 3]
```diff
@@ -0,0 +1,295 @@
...
+    }
+
+    if (userAccelerators.size === 0) {
+      return
+    }
+
+    // deep clone shortcuts and unset user shortcuts
+    const accelerators = new Map(this.keys)
+    userAccelerators.forEach((value, key) => {
+      accelerators.set(key, '')
```
Comment (Jocs) [inline src/main/shortcutHandler.js]: Why need to set the use set `key` to empty `string`?

File: src/main/shortcutHandler.js [hunk 4]
```diff
@@ -0,0 +1,295 @@
...
+        }
+      }
+      accelerators.set(userKey, userValue)
+    }
+
+    // update key bindings
+    this.keys = accelerators
+  }
+
+  get (id) {
```
Comment (Jocs) [inline src/main/shortcutHandler.js]: `get` is a `keyword` of JavaScript, it used to declare `get` and `set` properties. So I recommend not use this word as function name. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

File: src/main/cli.js [hunk 5]
```diff
@@ -0,0 +1,34 @@
+import { app } from 'electron'
```
Comment (Jocs) [inline src/main/cli.js]: Need we add some documents in doc folder and referred in the README.md file?

**Comment by Jocs** [comment]
>Add settings option keyboard-lang to overwrite keyboard language

I don't know whether we need it, you decide.

**Comment by Jocs** [comment]
Great! I have build the source code successfully on macOs! and it works well!

File: src/main/shortcutHandler.js [hunk 6]
```diff
@@ -0,0 +1,295 @@
...
+      ['paragraphHeading4', 'CmdOrCtrl+4'],
+      ['paragraphHeading5', 'CmdOrCtrl+5'],
+      ['paragraphHeading6', 'CmdOrCtrl+6'],
+      ['paragraphUpgradeHeading', 'CmdOrCtrl+='],
+      ['paragraphDegradeHeading', 'CmdOrCtrl+-'],
+      ['paragraphTable', 'CmdOrCtrl+T'],
+      ['paragraphCodeFences', 'CmdOrCtrl+Alt+C'],
+      ['paragraphQuoteBlock', 'CmdOrCtrl+Alt+Q'],
+      ['paragraphMathBlock', 'CmdOrCtrl+Alt+M'],
+      ['paragraphHtmlBlock', 'CmdOrCtrl+Alt+H'],
```
Comment (Jocs) [inline src/main/shortcutHandler.js]: That's strange! I can use `CmdOrCtrl+Alt+H` on dev and production(build version)! but I didn't see the `CmdOrCtrl+Alt+H` in the menu item. the accelerator after the item label is empty in the menu item.

File: src/main/shortcutHandler.js (hunk 2 above)
Comment (fxha) [reply src/main/shortcutHandler.js]: I'll will do that and create a `misc` folder so we can create templates for the end-user documentation and merge these files later.

File: src/main/cli.js (hunk 5 above)
Comment (fxha) [reply src/main/cli.js]: I'll will do that. See my comment above.

File: src/main/shortcutHandler.js (hunk 3 above)
Comment (fxha) [reply src/main/shortcutHandler.js]: Because we have to release the accelerators before duplicate check. If we don't unset the accelerators the following example will not work:

```
{
  "fileSave": "CmdOrCtrl+Shift+S",
  "fileSaveAs": "CmdOrCtrl+S"
}
```

because `CmdOrCtrl+S` and `CmdOrCtrl+Shift+S` are already in use.

**Comment by fxha** [comment]
>  > Add settings option keyboard-lang to overwrite keyboard language
>
>  I don't know whether we need it, you decide. Because I haven't encountered many issues here.

That's what I thought this morning.

File: src/main/shortcutHandler.js (hunk 6 above)
Comment (Jocs) [reply src/main/shortcutHandler.js]: You can see that the `HTML Block` accelerator is empty.

File: src/main/shortcutHandler.js (hunk 3 above)
Comment (Jocs) [reply src/main/shortcutHandler.js]: >Because we have to release the accelerators before duplicate check.

If we have already set the accelerator to empty string, what's the meaning of duplicate check?

Comment (Jocs) [reply src/main/shortcutHandler.js]:
```javascript
if (this.equalsAccelerators(value, userValue))  {}
```

is codes above always be `false`, because we set it to empty string?

File: src/main/shortcutHandler.js (hunk 6 above)
Comment (fxha) [reply src/main/shortcutHandler.js]: I found the problem: `Command+Alt+H` is defined as hide others (macOS only) and html block. Would you be okay with `Command+Alt+J` on macOS?

File: src/main/shortcutHandler.js (hunk 3 above)
Comment (fxha) [reply src/main/shortcutHandler.js]: No, we unset the keys because we know that we set them to another accelerator. Then we check for duplicates because we may changed `fileSave` to `Ctrl+T` but `Ctrl+T` already exists as `paragraphTable`. In this example `equalsAccelerators(...)` is `true` and we have to stop. In the example above `equalsAccelerators(...)` is always `false` because there are not duplicated accelerators.

File: src/main/shortcutHandler.js (hunk 6 above)
Comment (Jocs) [reply src/main/shortcutHandler.js]: Ok!

File: src/main/shortcutHandler.js (hunk 3 above)
Comment (Jocs) [reply src/main/shortcutHandler.js]: ha, I understand it after your explanation! thanks.

**Comment by Jocs** [comment]
@fxha I encounter a problem, I think it is not related to this PR, because it happened both on master and the PR branch.

The problem is 'after I run `npm run dev`' there is no UI, and the error below shown after I click any menu item.



Strange, I didn't change any code in main folder, have you encounter this problem, I think it maybe related to the OS or Electron special version.

**Comment by fxha** [comment]
@Jocs I do not experience any problems but it may be a problem with PR #539 because if the editor/window is initialized before the menu, then errors occur because the editor tries to load menu item which doesn't exist. I thought I fixed the problem and this should not happen. Can you run `npm install` and `npm run lint && npm run dev` again?

Edit: Why does it crash on `click` event?

**Comment by Jocs** [comment]
>Can you run npm install and npm run lint && npm run dev again?

Still can not start up!

>Why does it crash on click event?

Don't know yet! it run well yesterday, maybe I reinstall `node_modules` today ?

File: doc/keybindings.md [hunk 7]
```diff
@@ -0,0 +1,114 @@
+# Key Bindings
+
+All key bindings can be overwritten with the `keybindings.json` file. Each entry consists of a `id`/`accelerator` pair in JSON format.
```
[the remark this answers is not in the document]
Comment (fxha) [reply doc/keybindings.md]: Does [this commit](https://github.com/marktext/marktext/pull/543/commits/42b8936d8c7418aa98d92477e0e71b09f0718460) solve the problem for you? The user have to create the file.

[the remark this answers is not in the document]
Comment (Jocs) [reply doc/keybindings.md]: yes

**Comment by Jocs** [comment]
Have you finished all of this PR?

**Comment by fxha** [comment]
Yes, I did. Do you want to open an issue or are you working on the crash?

**Comment by Jocs** [comment]
I will work on the crash tomorrow night, It's too late today. I'll open an issue if I can not solve it tomorrow.

**Comment by Jocs** [comment]
How strange! the crash issue fixed itself after I merge this PR, and reinstall the dependences.

**Comment by Jocs** [comment]
I think you can update the `CHANGELOG` file? Maybe we can add this PR to v 0.14.xx because you add some new features.

**Comment by fxha** [comment]
Yeah, I forgot it. I think we can add it to v0.13.x because it's just a bug fix and a shortcut change.

**Comment by Jocs** [comment]
@fxha Sorry for I still don't know how to use the `cli`.


Do I need to some link or something else?

**Comment by Jocs** [comment]
>Yeah, I forgot it. I think we can add it to v0.13.x because it's just a bug fix and a shortcut change.

Ok, we can release a hotfix version after full test.

**Comment by fxha** [comment]
> Code fence menu item has no accelerator.

Yes, I renamed the accelerator id. I'll fix it alongside the changelog.

**Comment by Jocs** [comment]
`Copy as HTML` has no accelerator, Do we need set accelerator to this menu item?

**Comment by fxha** [comment]
> Copy as HTML has no accelerator, Do we need set accelerator to this menu item?

I noticed this too but it never had a shortcut. Usually you don't copy as HTML. I think it's fine as it is.

**Comment by Jocs** [comment]
>I think it's fine as it is.

Ok.
